export const PREDEFINED_SKILLS = [
  // Leadership & Management
  "Project Management",
  "Team Leadership",
  "Strategic Planning",
  "Change Management",
  "Operations Management",
  "Performance Management",
  "Stakeholder Management",
  "Risk Management",
  "Resource Allocation",
  "Budgeting",
  "Business Analysis",
  "Business Development",
  "Process Improvement",
  "Decision Making",
  "Conflict Resolution",
  "Negotiation",
  "Mentoring",
  "Coaching",
  "Recruitment",
  "Talent Management",
  "Succession Planning",
  "Organizational Design",

  // Communication & Collaboration
  "Communication",
  "Public Speaking",
  "Presentation Skills",
  "Active Listening",
  "Interpersonal Skills",
  "Cross-functional Collaboration",
  "Customer Relationship Management",
  "Vendor Management",
  "Networking",

  // HR & People
  "HR Management",
  "Employee Engagement",
  "Onboarding",
  "Training & Development",
  "Diversity & Inclusion",
  "Payroll Management",
  "Labor Relations",
  "Compensation & Benefits",

  // Finance & Legal
  "Finance",
  "Financial Analysis",
  "Accounting",
  "Auditing",
  "Procurement",
  "Contract Management",
  "Legal Compliance",
  "Regulatory Affairs",

  // Marketing & Sales
  "Marketing",
  "Digital Marketing",
  "Brand Management",
  "Market Research",
  "Sales",
  "Lead Generation",
  "Customer Support",
  "Content Creation",
  "Copywriting",
  "Event Planning",

  // IT & Digital
  "IT Management",
  "Software Development",
  "UI/UX Design",
  "Cloud Computing",
  "Cybersecurity",
  "Data Analysis",
  "Data Visualization",
  "Machine Learning",
  "DevOps",
  "QA Testing",
  "Product Management",
  "Agile Methodologies",
  "Scrum",
  "Kanban",
  "Technical Support",

  // General & Soft Skills
  "Time Management",
  "Problem Solving",
  "Creativity",
  "Critical Thinking",
  "Adaptability",
  "Emotional Intelligence",
  "Attention to Detail",
  "Decision Making",
  "Organizational Skills",
  "Multitasking",
  "Remote Work",
  "Customer Orientation",
  "Presentation Skills",
  "Documentation",
];